theme = "kanagawa-dragon"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
shell = ["pwsh","-c"]

[editor.soft-wrap]
enable = true
max-wrap = 30
wrap-indicator = ""

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.smart-tab]
enable = true

[editor.file-picker]
hidden = false

[editor.statusline]
mode.normal = "   NORMAL   "
mode.insert = "-- INSERT --"
mode.select = ">> SELECT <<"
left = ["spacer","mode","read-only-indicator","register","selections","spinner","diagnostics"]
center = ["primary-selection-length","spacer","spacer","spacer","position"]
right = ["version-control","file-modification-indicator","file-name","position-percentage","spacer"]

[keys.normal]
  # tweaks
a = ["append_mode", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]
C-q = "record_macro"
q = "replay_macro"
  # line selections
x = "extend_line_below"
X = "extend_line_above"
C-x = "extend_to_line_bounds"
  # move via subwords
A-w = "move_next_sub_word_start"
A-e = "move_next_sub_word_end"
A-b = "move_prev_sub_word_start"
  # match inner subword (if not at start)
A-q = ["move_prev_sub_word_start","move_next_sub_word_end"]
  # select to end/start of line
L = "extend_to_line_end"
H = "extend_to_first_nonwhitespace"
  # delete line
D = ["extend_to_line_bounds", "delete_selection"]
A-D = ["extend_to_line_bounds", "change_selection", "normal_mode"] 
  # move line up/down
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"] 
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
  # advanced moves
# M = []

[keys.insert]
k = { j = "normal_mode" }
C-q = "collapse_selection"
